apiVersion: apps/v1
kind: Deployment
metadata:
  name: fighting-characters
  namespace: fighting-characters
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fighting-characters
  template:
    metadata:
      labels:
        app: fighting-characters
    spec:
      containers:
        - name: fighting-characters
          image: 372595555088.dkr.ecr.ap-south-1.amazonaws.com/fightingcharacters:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 5000


