apiVersion: apps/v1
kind: Deployment
metadata:
  name: fighting-characters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fighting-characters
  template:
    metadata:
      labels:
        app: fighting-characters
    spec:
      initContainers:
        - name: wait-mongo
          image: mongo:6.0
          command: ['sh','-c','until mongosh --host mongo --eval "db.adminCommand({ping:1})" >/dev/null 2>&1; do echo waiting for mongo; sleep 3; done']
      containers:
        - name: fighting-characters
          image: <will-be-set-by-CD>   # ה-CD כבר מחליף
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/fightingcharacters"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
