apiVersion: apps/v1
kind: Deployment
metadata:
  name: fighting-characters
  labels:
    app: fighting-characters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fighting-characters
  template:
    metadata:
      labels:
        app: fighting-characters
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: wait-mongo
          image: mongo:6.0
          command:
            - sh
            - -c
            - |
              for i in $(seq 1 120); do
                mongosh --host mongo --quiet --eval 'db.adminCommand({ping:1})' >/dev/null 2>&1 && exit 0
                echo "[$(date -Is)] waiting for mongo..."
                sleep 3
              done
              echo "Mongo did not become ready in time" >&2
              exit 1
      containers:
        - name: fighting-characters
          image: <will-be-set-by-CD>  
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DB_NAME
              value: "fightingcharacters"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/fightingcharacters"
            - name: MONGODB_URI
              value: "mongodb://mongo:27017/fightingcharacters"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/fightingcharacters"
          startupProbe:
            httpGet: { path: /health, port: 5000 }
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet: { path: /health, port: 5000 }
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 6
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits:   { cpu: 500m, memory: 512Mi }
