apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fighting-characters
type: Opaque
stringData:
  # Must match mongodb-values.yaml
  MONGO_URI: "mongodb://appuser:AppUser_Str0ng!@mongo-mongodb.fighting-characters.svc.cluster.local:27017/fighting_characters?authSource=admin"
  SECRET_KEY: "prod-secret"
