apiVersion: v1
kind: Service
metadata:
  name: fighting-characters
  namespace: fighting-characters
  labels:
    app: fighting-characters
spec:
  selector:
    app: fighting-characters
  ports:
    - name: http
      port: 5000
      targetPort: http
