apiVersion: apps/v1
kind: Deployment
metadata:
  name: fighting-characters
  namespace: fighting-characters
spec:
  replicas: 1
  progressDeadlineSeconds: 900
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: fighting-characters
  template:
    metadata:
      labels:
        app: fighting-characters
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: fighting-characters
          image: 372595555088.dkr.ecr.ap-south-1.amazonaws.com/fightingcharacters:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000

          # Entry script resilient: תומך גם במבנה /app/app/app.py וגם /app/app.py
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              # יישור imports: הוסף שתי ספריות ל-PYTHONPATH
              export PYTHONPATH="/app:/app/app:${PYTHONPATH:-}"
              if [ -f /app/app/app.py ]; then
                cd /app/app
                MOD="app:app"
              elif [ -f /app/app.py ]; then
                cd /app
                MOD="app:app"
              else
                echo "Cannot find app.py at /app/app/app.py or /app/app.py"
                exit 1
              fi
              echo "[startup] Using module: $MOD in $(pwd) PYTHONPATH=$PYTHONPATH"
              exec gunicorn -w 3 -b 0.0.0.0:5000 "$MOD" --timeout 60 --graceful-timeout 30

          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/fighting_characters"
            - name: DB_NAME
              value: "fighting_characters"
            - name: COLLECTION_NAME
              value: "characters"
            - name: SECRET_KEY
              value: "prod-secret"
            - name: SEED_ON_START
              value: "false"

          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 5"]

          # פרובים נדיבים כדי למנוע false-negative בזמן עלייה
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: fighting-characters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          resources:
