apiVersion: apps/v1
kind: Deployment
metadata:
  name: fighting-characters
  namespace: fighting-characters
  labels:
    app: fighting-characters
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fighting-characters
  template:
    metadata:
      labels:
        app: fighting-characters
    spec:
      containers:
        - name: app
          image: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/fighting-characters:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
