apiVersion: v1
kind: Service
metadata:
  name: fighting-characters
  namespace: fighting-characters
spec:
  selector:
    app: fighting-characters
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
